import pytest
from selenium import webdriver
from selenium.webdriver.common.by import By
import time
from test_login import test_valid_login

@pytest.fixture
def driver():
    driver = webdriver.Chrome()
    driver.maximize_window()
    yield driver
    driver.quit()

def test_checkout_with_login(driver):
    test_valid_login(driver)
    time.sleep(10)
    driver.find_element(By.XPATH, "//a[contains(@href , 'route=common/home')]").click()
    time.sleep(10)
    my_account_link = driver.find_element(By.NAME, "search")
    my_account_link.clear()
    my_account_link.send_keys("Touch")
    time.sleep(3)
    driver.find_element(By.CSS_SELECTOR, ".btn.btn-light.btn-lg").click()
    time.sleep(5)
    driver.execute_script("window.scrollBy(0, 500);")
    time.sleep(5)
    driver.find_element(By.XPATH, "/html/body/main/div[2]/div/div/div[5]/div[2]/div/div[1]/a/img").click()
    time.sleep(10)
    add_to_cart_button = driver.find_element(By.XPATH, "//button[contains(@id, 'button-cart')]")
    add_to_cart_button.click()
    time.sleep(10)

    driver.find_element(By.XPATH, "//span[contains(text(), 'Shopping Cart')]").click()
    time.sleep(2)
    driver.execute_script("window.scrollBy(0, 500);")
    time.sleep(2)
    driver.find_element(By.XPATH, "/html/body/main/div[2]/div/div/div[3]/div[2]/a").click()
    time.sleep(2)

    try:
        driver.find_element(By.XPATH, "//input[contains(@id, 'input-shipping-existing')]").click()
        time.sleep(2)
        driver.find_element(By.XPATH, "//select[contains(@name, 'address_id')]").click()
        time.sleep(2)
        driver.find_element(By.XPATH, "//option[contains(@value, '1143')]").click()
        time.sleep(2)

    except Exception:
        driver.find_element(By.XPATH, "//input[contains(@id, 'input-shipping-mew')]").click()
        time.sleep(2)
        driver.find_element(By.XPATH, "//input[contains(@name, 'firstname')]").send_keys("Jennifer")
        driver.find_element(By.XPATH, "//input[contains(@name, 'lastname')]").send_keys("Candy")
        time.sleep(5)

        driver.find_element(By.XPATH, "//input[contains(@name, 'company')]").send_keys("My Company")
        driver.find_element(By.XPATH, "//input[contains(@name, 'address_1')]").send_keys("quan 1")
        driver.find_element(By.XPATH, "//input[contains(@name, 'city')]").send_keys("Thành Phố Hồ Chí Minh")
        driver.find_element(By.XPATH, "//input[contains(@name, 'postcode')]").send_keys("70000")
        time.sleep(2)
        driver.find_element(By.XPATH, "//select[contains(@name, 'country_id')]").click()
        time.sleep(2)
        driver.find_element(By.XPATH, "//option[contains(@value, '230')]").click()

        driver.execute_script("window.scrollBy(0, 500);")
        time.sleep(2)

        driver.execute_script("window.scrollBy(0, 500);")  # Cuộn xuống 500px
        time.sleep(2)
        driver.find_element(By.XPATH, "//select[contains(@name, 'zone_id')]").click()
        time.sleep(2)
        driver.find_element(By.XPATH, "//option[contains(@value, '3780')]").click()
        time.sleep(2)
        driver.find_element(By.XPATH, "//button[contains(@id, 'button-shipping-address')]").click()
        time.sleep(2)

    driver.execute_script("window.scrollBy(0, -1000);")
    time.sleep(2)
    driver.find_element(By.XPATH, "//button[contains(@id, 'button-shipping-methods')]").click()
    time.sleep(2)
    driver.find_element(By.XPATH, "//input[contains(@id, 'input-shipping-method-flat-flat')]").click()
    time.sleep(2)
    driver.find_element(By.XPATH, "//div[@class='text-end']/button[@id='button-shipping-method']").click()
    time.sleep(2)
    driver.find_element(By.XPATH, "//button[contains(@id, 'button-payment-methods')]").click()
    time.sleep(2)
    driver.find_element(By.XPATH, "//input[contains(@id, 'input-payment-method-cod-cod')]").click()
    time.sleep(2)
    driver.find_element(By.XPATH, "//div[@class='text-end']/button[@id='button-payment-method']").click()
    time.sleep(2)
    driver.execute_script("window.scrollBy(0, 500);")
    time.sleep(2)
    driver.find_element(By.XPATH, "//button[contains(@id, 'button-confirm')]").click()
    time.sleep(2)
    # # driver.find_element(By.XPATH, "/html/body/main/div[2]/div[2]/div/div[3]/div[2]/a").click()
    #
    order_success = driver.find_element(By.XPATH, "//h1[contains(text(), 'Your order has been placed!')]")
    assert order_success.is_displayed()

def test_checkout_by_register_new_account(driver):
    driver.get("https://demo.opencart.com/")
    driver.execute_script("window.scrollBy(0, 500);")  # Cuộn xuống 500px
    time.sleep(2)
    my_account_link = driver.find_element(By.NAME, "search")
    my_account_link.clear()
    my_account_link.send_keys("Touch")
    time.sleep(3)
    driver.find_element(By.CSS_SELECTOR, ".btn.btn-light.btn-lg").click()
    time.sleep(5)
    driver.execute_script("window.scrollBy(0, 500);")
    time.sleep(5)
    driver.find_element(By.XPATH, "/html/body/main/div[2]/div/div/div[5]/div[2]/div/div[1]/a/img").click()
    time.sleep(10)

    add_to_cart_button = driver.find_element(By.XPATH, "//button[contains(text(), 'Add to Cart')]")
    add_to_cart_button.click()
    time.sleep(6)

    driver.find_element(By.XPATH, "//a[contains(@href, 'route=checkout/checkout')]").click()
    time.sleep(6)

    driver.find_element(By.XPATH, "//label[contains(text(), 'Register Account')]"). click()
    time.sleep(2)

    driver.find_element(By.XPATH, "//input[contains(@id, 'input-firstname')]").send_keys("Jennifer")
    driver.find_element(By.XPATH, "//input[contains(@id, 'input-lastname')]").send_keys("Candy")
    driver.find_element(By.XPATH, "//input[contains(@id, 'input-email')]").send_keys("jc1@gmail.com")
    time.sleep(5)

    driver.find_element(By.XPATH, "//input[contains(@id, 'input-shipping-company')]").send_keys("My Company")
    driver.find_element(By.XPATH, "//input[contains(@id, 'input-shipping-address-1')]").send_keys("quan 1")
    driver.find_element(By.XPATH, "//input[contains(@id, 'input-shipping-city')]").send_keys("Thành Phố Hồ Chí Minh")
    driver.find_element(By.XPATH, "//input[contains(@id, 'input-shipping-postcode')]").send_keys("70000")
    time.sleep(2)
    driver.find_element(By.XPATH, "//select[contains(@id, 'input-shipping-country')]").click()
    time.sleep(2)
    driver.find_element(By.XPATH, "//option[contains(@value, '230')]").click()

    driver.execute_script("window.scrollBy(0, 500);")  # Cuộn xuống 500px
    time.sleep(2)
    driver.find_element(By.XPATH, "//select[contains(@name, 'shipping_zone_id')]").click()
    time.sleep(2)
    driver.find_element(By.XPATH, "//option[contains(@value, '3780')]").click()
    time.sleep(2)
    driver.find_element(By.XPATH, "//input[contains(@id, 'input-password')]").send_keys("123456")
    time.sleep(2)
    driver.find_element(By.XPATH, "//input[contains(@id, 'input-newsletter')]").click()
    time.sleep(2)
    driver.find_element(By.XPATH, "//input[contains(@id, 'input-register-agree')]").click()
    time.sleep(2)
    driver.find_element(By.XPATH, "//button[contains(@id, 'button-register')]").click()
    time.sleep(5)
    driver.execute_script("window.scrollBy(0, -1000);")
    time.sleep(2)
    driver.find_element(By.XPATH, "//button[contains(@id, 'button-shipping-methods')]").click()
    time.sleep(2)
    driver.find_element(By.XPATH, "//input[contains(@id, 'input-shipping-method-flat-flat')]").click()
    time.sleep(2)
    driver.find_element(By.XPATH, "//div[@class='text-end']/button[@id='button-shipping-method']").click()
    time.sleep(2)
    driver.find_element(By.XPATH, "//button[contains(@id, 'button-payment-methods')]").click()
    time.sleep(2)
    driver.find_element(By.XPATH, "//input[contains(@id, 'input-payment-method-cod-cod')]").click()
    time.sleep(2)
    driver.find_element(By.XPATH, "//div[@class='text-end']/button[@id='button-payment-method']").click()
    time.sleep(2)
    driver.execute_script("window.scrollBy(0, 500);")
    time.sleep(2)
    driver.find_element(By.XPATH, "//button[contains(@id, 'button-confirm')]").click()
    time.sleep(2)


    order_success = driver.find_element(By.XPATH, "//h1[contains(text(), 'Your order has been placed!')]")
    assert order_success.is_displayed()

def test_checkout_as_guest(driver):
    driver.get("https://demo.opencart.com/")
    driver.execute_script("window.scrollBy(0, 500);")  # Cuộn xuống 500px
    time.sleep(2)
    my_account_link = driver.find_element(By.NAME, "search")
    my_account_link.clear()
    my_account_link.send_keys("Touch")
    time.sleep(3)
    driver.find_element(By.CSS_SELECTOR, ".btn.btn-light.btn-lg").click()
    time.sleep(5)
    driver.execute_script("window.scrollBy(0, 500);")
    time.sleep(5)
    driver.find_element(By.XPATH, "/html/body/main/div[2]/div/div/div[5]/div[2]/div/div[1]/a/img").click()
    time.sleep(10)

    add_to_cart_button = driver.find_element(By.XPATH, "//button[contains(text(), 'Add to Cart')]")
    add_to_cart_button.click()
    time.sleep(6)

    driver.find_element(By.XPATH, "//a[contains(@href, 'route=checkout/checkout')]").click()
    time.sleep(6)

    driver.find_element(By.XPATH, "//label[contains(text(), 'Guest Checkout')]"). click()
    time.sleep(2)

    driver.find_element(By.XPATH, "//input[contains(@id, 'input-firstname')]").send_keys("Jennifer")
    driver.find_element(By.XPATH, "//input[contains(@id, 'input-lastname')]").send_keys("Candy")
    driver.find_element(By.XPATH, "//input[contains(@id, 'input-email')]").send_keys("jcandie@gmail.com")
    time.sleep(5)

    driver.find_element(By.XPATH, "//input[contains(@id, 'input-shipping-company')]").send_keys("My Company")
    driver.find_element(By.XPATH, "//input[contains(@id, 'input-shipping-address-1')]").send_keys("quan 1")
    driver.find_element(By.XPATH, "//input[contains(@id, 'input-shipping-city')]").send_keys("Thành Phố Hồ Chí Minh")
    driver.find_element(By.XPATH, "//input[contains(@id, 'input-shipping-postcode')]").send_keys("70000")
    time.sleep(2)
    driver.find_element(By.XPATH, "//select[contains(@id, 'input-shipping-country')]").click()
    time.sleep(2)
    driver.find_element(By.XPATH, "//option[contains(@value, '230')]").click()

    driver.execute_script("window.scrollBy(0, 500);")  # Cuộn xuống 500px
    time.sleep(2)
    driver.find_element(By.XPATH, "//select[contains(@name, 'shipping_zone_id')]").click()
    time.sleep(2)
    driver.find_element(By.XPATH, "//option[contains(@value, '3780')]").click()
    time.sleep(2)
    driver.find_element(By.XPATH, "//input[contains(@id, 'input-newsletter')]").click()
    time.sleep(2)
    driver.find_element(By.XPATH, "//button[contains(@id, 'button-register')]").click()
    time.sleep(2)
    driver.execute_script("window.scrollBy(0, -1000);")
    time.sleep(2)
    driver.find_element(By.XPATH, "//button[contains(@id, 'button-shipping-methods')]").click()
    time.sleep(2)
    driver.find_element(By.XPATH, "//input[contains(@id, 'input-shipping-method-flat-flat')]").click()
    time.sleep(2)
    driver.find_element(By.XPATH, "//div[@class='text-end']/button[@id='button-shipping-method']").click()
    time.sleep(2)
    driver.find_element(By.XPATH, "//button[contains(@id, 'button-payment-methods')]").click()
    time.sleep(2)
    driver.find_element(By.XPATH, "//input[contains(@id, 'input-payment-method-cod-cod')]").click()
    time.sleep(2)
    driver.find_element(By.XPATH, "//div[@class='text-end']/button[@id='button-payment-method']").click()
    time.sleep(2)
    driver.execute_script("window.scrollBy(0, 500);")
    time.sleep(2)
    driver.find_element(By.XPATH, "//button[contains(@id, 'button-confirm')]").click()
    time.sleep(2)


    order_success = driver.find_element(By.XPATH, "//h1[contains(text(), 'Your order has been placed!')]")
    assert order_success.is_displayed()

